# From: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
# See also: https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md
# See also: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

name: test

on:
  push:
    branches:
      - 'extended'
      - 'fix-ci'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/greyltc-org/archlinux-aur:yay
          options: -v ${{ github.workspace }}:/ros2-galactic-pkgbuild
          run: bash /ros2-galactic-pkgbuild/.github/workflows/test.bash
